"""add table data_contract_extrinsic

Revision ID: 42310d504350
Revises: 8349d998d804
Create Date: 2021-03-18 06:40:07.154359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42310d504350'
down_revision = '8349d998d804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_contract_extrinsic',
        sa.Column('block_id', sa.Integer(), nullable=False),
        sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
        sa.Column('from_address', sa.String(length=48), nullable=False),
        sa.Column('to_address', sa.String(length=48), nullable=True),
        sa.Column('contract_address', sa.String(length=48), nullable=True),
        sa.Column('message_name', sa.String(length=256), nullable=True),
        sa.Column('message_args', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('block_id', 'extrinsic_idx', name="block_extrinsic")
    )
    op.create_index(op.f('ix_data_contract_extrinsic_from_address'), 'data_contract_extrinsic', ['from_address'], unique=False)
    op.create_index(op.f('ix_data_contract_extrinsic_to_address'), 'data_contract_extrinsic', ['to_address'], unique=False)
    op.create_index(op.f('ix_data_contract_extrinsic_contract_address'), 'data_contract_extrinsic', ['contract_address'], unique=False)
    op.create_index(op.f('ix_data_contract_extrinsic_message_name'), 'data_contract_extrinsic', ['message_name'], unique=False)

    op.add_column('data_extrinsic', sa.Column('to_address', sa.String(length=48), nullable=True))
    op.create_index(op.f('ix_data_extrinsic_to_address'), 'data_extrinsic', ['to_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_contract_extrinsic')
    op.drop_column('data_extrinsic', 'to_address')

    op.drop_index(op.f('ix_data_contract_extrinsic_from_address'), table_name='data_contract_extrinsic')
    op.drop_index(op.f('ix_data_contract_extrinsic_to_address'), table_name='data_contract_extrinsic')
    op.drop_index(op.f('ix_data_contract_extrinsic_contract_address'), table_name='data_contract_extrinsic')
    op.drop_index(op.f('ix_data_contract_extrinsic_message_name'), table_name='data_contract_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_to_address'), table_name='data_extrinsic')
    # ### end Alembic commands ###
