"""add name to data_contract

Revision ID: 5e75cbb22b51
Revises: c8af8b4a3ecf
Create Date: 2021-03-09 03:02:32.203932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e75cbb22b51'
down_revision = 'c8af8b4a3ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_contract', sa.Column('name', sa.String(128), nullable=True))
    op.alter_column('data_contract_instance', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('data_contract_instance', 'symbol',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_contract', "name")
    op.alter_column('data_contract_instance', 'name',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    op.alter_column('data_contract_instance', 'symbol',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
